# Generated by Django 5.1.5 on 2025-01-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livre',
            old_name='name',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='emprunteur',
        ),
    ]
