# Generated by Django 5.1.5 on 2025-02-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_emprunt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='date_retour',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='livre',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='objet',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprunt',
            name='rendu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.membre'),
        ),
    ]
